services:
  database:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${PG_USER:-products}
      POSTGRES_PASSWORD: ${PG_PASSWORD:-123321}
      POSTGRES_DB: ${PG_DATABASE:-products}
    ports:
      - "${PG_PORT:-5432}:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
